### PR TITLE
Remove dependency on storable-complex

### PR DESCRIPTION
**Pull request by robinbb**

### CODE REVIEW

**Comment by ldamewood** [comment]
Remind me, what is the reason we are not using the stackage version of hmatrix?

**Comment by ldamewood** [comment]
Why is this removal needed? It's not removed in the main hmatrix repo, which works in stackage AFAIK.

**Comment by robinbb** [comment]
@ldamewood The build errors corrected by these code changes:
https://github.com/LeapYear/hmatrix/commit/d651f4b13240208c02424fbe566d1394783e5626
https://github.com/LeapYear/hmatrix/commit/cd598a8e15e1a3730e895217b4533dd7c9dcd65e
https://github.com/LeapYear/hmatrix/commit/f4c9e3e78cd602dcaec9eca78bd6f1437ec2d18e

**Comment by robinbb** [comment]
The removal is not "needed" but it reduces the number of dependencies that we have. There is no use of storable-complex in the package.

**Pull request merged**
